In [1]:
import pandas as pd
import json

In [ ]:
data = pd.read_csv('Data Papua Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,51.4,49.4,100.7
1,5/9/01,66.8,64.3,131.1
2,10/14/01,58.1,56.5,114.7
3,15-19,43.7,39.7,83.5
4,20-24,35.6,31.6,67.1
5,25-29,44.9,41.2,86.1
6,30-34,46.5,40.5,87.1
7,35-39,48.7,41.7,90.4
8,40-44,41.5,35.1,76.6
9,45-49,32.1,28.5,60.6
10,50-54,27.9,24.5,52.3
11,55-59,19.4,18.7,38.1
12,60-64,18.3,16.0,34.2
13,65-69,10.6,10.9,21.5
14,70-74,8.4,7.4,15.8
15,75+,7.1,6.8,13.8
16,Jumlah/Total,560.9,512.7,1073.6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [11]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
display(df)
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) * 1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_semua = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_semua
}])

display(df_final)

   Kelompok Umur  Penduduk (Laki-Laki) (Ribu)  Penduduk (Perempuan) (Ribu)
0         4/1/00                         51.4                         49.4
1         5/9/01                         66.8                         64.3
2       10/14/01                         58.1                         56.5
3          15-19                         43.7                         39.7
4          20-24                         35.6                         31.6
5          25-29                         44.9                         41.2
6          30-34                         46.5                         40.5
7          35-39                         48.7                         41.7
8          40-44                         41.5                         35.1
9          45-49                         32.1                         28.5
10         50-54                         27.9                         24.5
11         55-59                         19.4                         18.7
12         60-64                         18.3                         16.0
13         65-69                         10.6                         10.9
14         70-74                          8.4                          7.4
15           75+                          7.1                          6.8
16  Jumlah/Total                        560.9                        512.7

   laki_laki  perempuan  total_keseluruhan
0     560900     512700            1073600

In [12]:
df_final.to_csv('jumlah_penduduk_papua.csv', index='False')
df_final.to_json('jumlah_penduduk_papua.json', orient='records')