In [50]:
import pandas as pd

laki = pd.read_csv(
    "Data_Kalimantan_Timur_Laki_laki_Kotor.csv",
    sep=','
)


perempuan = pd.read_csv(
    "Data_Kalimantan_Timur_Perempuan_Kotor.csv",
    sep=','
)

display(laki)
display(perempuan)


df_gabung = pd.DataFrame({
    'wilayah': laki.iloc[:,0],
    'laki_laki': laki.iloc[:,1],
    'perempuan': perempuan.iloc[:,1]
})

display(df_gabung)


df_gabung.to_csv(
    'Data_Kalimantan_Timur_Gabungan.csv',
    index=False
)

,Kelompok Umur,[SUPAS2015] Proyeksi Penduduk Menurut Jenis Kelamin dan Kelompok Umur (Male) (Jiwa)
0,NaN,2025
1,4/1/00,153711
2,5/9/01,151810
3,10/14/01,150656
4,15-19,151193
5,20-24,154665
6,25-29,158041
7,30-34,154819
8,35-39,150707
9,40-44,149971
10,45-49,145465
11,50-54,138118
12,55-59,117803
13,60-64,90955
14,65-69,64089
15,70-74,37557
16,75+,29170
17,Kalimantan Timur,1998730
18,NaN,NaN
19,Catatan,"Sumber: BPS, Proyeksi Penduduk Kabupaten/Kota ..."

,Kelompok Umur,[SUPAS2015] Proyeksi Penduduk Menurut Jenis Kelamin dan Kelompok Umur (Perempuan) (Jiwa)
0,NaN,2025
1,4/1/00,150127
2,5/9/01,148775
3,10/14/01,144694
4,15-19,144885
5,20-24,148629
6,25-29,152011
7,30-34,150184
8,35-39,145281
9,40-44,142641
10,45-49,133236
11,50-54,118586
12,55-59,101832
13,60-64,81073
14,65-69,56637
15,70-74,32945
16,75+,29242
17,Kalimantan Timur,1880778
18,NaN,NaN
19,Catatan,"Sumber: BPS, Proyeksi Penduduk Kabupaten/Kota ..."

,wilayah,laki_laki,perempuan
0,NaN,2025,2025
1,4/1/00,153711,150127
2,5/9/01,151810,148775
3,10/14/01,150656,144694
4,15-19,151193,144885
5,20-24,154665,148629
6,25-29,158041,152011
7,30-34,154819,150184
8,35-39,150707,145281
9,40-44,149971,142641
10,45-49,145465,133236
11,50-54,138118,118586
12,55-59,117803,101832
13,60-64,90955,81073
14,65-69,64089,56637
15,70-74,37557,32945
16,75+,29170,29242
17,Kalimantan Timur,1998730,1880778
18,NaN,NaN,NaN
19,Catatan,"Sumber: BPS, Proyeksi Penduduk Kabupaten/Kota ...","Sumber: BPS, Proyeksi Penduduk Kabupaten/Kota ..."

In [52]:
import pandas as pd


total_laki = int(df_gabung.iloc[17,1])

total_perempuan = int(df_gabung.iloc[17,2])


total_keseluruhan = (
    total_laki + total_perempuan
)

# dataframe final
df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)


df_final.to_csv(
    'jumlah_penduduk_kalimantan_timur.csv',
    index=False
)


df_final.to_json(
    'jumlah_penduduk_kalimantan_timur.json',
    orient='records',
    indent=4
)

   laki_laki  perempuan  total_keseluruhan
0    1998730    1880778            3879508