In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv("Data Jawa Timur Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,1498.0,1438.2,2936.2
1,5/9/01,1432.3,1370.0,2802.4
2,10/14/01,1496.4,1433.0,2929.4
3,15-19,1515.6,1431.5,2947.1
4,20-24,1538.7,1461.2,2999.9
5,25-29,1576.4,1508.9,3085.3
6,30-34,1580.6,1533.4,3114.0
7,35-39,1574.0,1554.6,3128.6
8,40-44,1541.9,1547.3,3089.1
9,45-49,1517.4,1555.6,3073.0
10,50-54,1408.7,1464.0,2872.6
11,55-59,1278.9,1349.9,2628.8
12,60-64,1073.3,1153.2,2226.5
13,65-69,838.4,912.3,1750.7
14,70-74,582.0,659.3,1241.3
15,75+,525.9,738.5,1264.4
16,Jumlah/Total,20978.5,21110.8,42089.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [5]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0   20978500   21110800           42089300

In [6]:
df_final.to_csv('jumlah_penduduk_jawa_timur.csv', index=False)
df_final.to_json('jumlah_penduduk_jawa_timur.json', orient='records')