In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv('Data Papua Barat Kotor.csv', skiprows=2)
display(data)
display(data.info())

           Unnamed: 0 Laki-laki Perempuan   Total
0                 NaN      2025      2025    2025
1              Fakfak     46535     44906   91441
2             Kaimana     35208     32587   67795
3       Teluk Wondama     24365     22230   46595
4       Teluk Bintuni     52794     39215   92009
5           Manokwari    107700    100321  208021
6      Sorong Selatan         -         -       -
7              Sorong         -         -       -
8          Raja Ampat         -         -       -
9            Tambrauw         -         -       -
10            Maybrat         -         -       -
11  Manokwari Selatan     20332     19239   39571
12   Pegunungan Arfak     21490     20723   42213
13        Kota Sorong         -         -       -
14        Papua Barat    308424    279221  587645

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  14 non-null     object
 1   Laki-laki   15 non-null     object
 2   Perempuan   15 non-null     object
 3   Total       15 non-null     object
dtypes: object(4)
memory usage: 612.0+ bytes

None

In [6]:
df_total = data[data['Unnamed: 0'].str.contains('Papua Barat', na=False, case=False)]

total_laki = int(pd.to_numeric(df_total['Laki-laki'].iloc[0]))
total_perempuan = int(pd.to_numeric(df_total['Perempuan'].iloc[0]))
total_keseluruhan = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     308424     279221             587645

In [8]:
df_final.to_csv('jumlah_penduduk_papua_barat.csv', index=False)
df_final.to_json('jumlah_penduduk_papua_barat.json', orient='records', indent=4)