In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv('Data Sulawesi Selatan Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,404.3,394.5,806.1
1,5/9/01,366.1,354.0,724.5
2,10/14/01,369.4,344.7,704.9
3,15-19,421.5,392.1,808.3
4,20-24,415.3,397.0,813.9
5,25-29,402.4,394.0,799.6
6,30-34,379.3,378.6,763.2
7,35-39,348.8,354.7,708.6
8,40-44,323.6,334.0,660.9
9,45-49,300.3,317.8,622.5
10,50-54,263.6,286.4,555.8
11,55-59,222.8,249.9,478.5
12,60-64,177.3,207.1,390.7
13,65-69,129.5,158.0,292.4
14,70-74,88.4,113.8,205.8
15,75+,89.4,134.5,227.4
16,Jumlah/Total,4702.0,4811.3,9563.1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [4]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    4702000    4811300            9513300

In [5]:
df_final.to_csv('jumlah_penduduk_sulawesi_selatan.csv', index=False)
df_final.to_json('jumlah_penduduk_sulawesi_selatan.json', orient='records')