In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv("Data Yogyakarta Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,123.1,118.2,241.4
1,5/9/01,124.6,119.6,244.2
2,10/14/01,128.3,123.0,251.3
3,15-19,133.9,127.1,260.9
4,20-24,138.1,132.4,270.5
5,25-29,137.9,134.0,271.9
6,30-34,135.1,132.9,268.0
7,35-39,134.5,133.8,268.3
8,40-44,133.0,133.7,266.7
9,45-49,132.3,135.9,268.2
10,50-54,125.1,130.7,255.9
11,55-59,117.1,125.2,242.3
12,60-64,100.7,110.5,211.2
13,65-69,81.4,91.7,173.0
14,70-74,58.3,69.2,127.5
15,75+,66.9,93.5,160.4
16,Jumlah/Total,1870.1,1911.4,3781.6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [10]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])

df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]

total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) *1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]) * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    1870100    1911400            3781500

In [11]:
df_final.to_csv('jumlah_penduduk_yogyakarta.csv', index=False)
df_final.to_json('jumlah_penduduk_yogyakarta.json', orient='records')