In [27]:
import pandas as pd


data = pd.read_csv(
    "Data_Kalimantan_Barat_Kotor.csv",
    sep=';'
)

display(data.tail())

total_laki = 2957074
total_perempuan = 2808956

total_keseluruhan = (
    total_laki + total_perempuan
)

# dataframe final
df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv
df_final.to_csv(
    'jumlah_penduduk_kalimantan_barat.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_kalimantan_barat.json',
    orient='records',
    indent=4
)

   Jumlah penduduk menurut jenis kelamin Unnamed: 1 Unnamed: 2
13                               109.565    105.557        NaN
14                                78.399     78.028        NaN
15                                51.586     53.403        NaN
16                                41.821     49.605        NaN
17                              2957.074   2808.956      Total

   laki_laki  perempuan  total_keseluruhan
0    2957074    2808956            5766030