In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv("Data Sulawesi Barat Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,74.6,72.9,147.5
1,5/9/01,69.7,67.9,137.6
2,10/14/01,67.6,65.9,133.6
3,15-19,70.7,66.2,136.9
4,20-24,68.9,64.6,133.5
5,25-29,67.1,63.9,131.0
6,30-34,63.1,60.3,123.4
7,35-39,56.8,54.9,111.7
8,40-44,51.2,50.0,101.2
9,45-49,46.4,45.5,91.9
10,50-54,39.7,39.2,78.9
11,55-59,32.1,32.1,64.2
12,60-64,24.9,25.4,50.3
13,65-69,17.3,18.2,35.5
14,70-74,11.4,12.5,23.9
15,75+,11.0,13.3,24.3
16,Jumlah/Total,772.7,752.7,1525.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [4]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     772700     752700            1525400

In [5]:
df_final.to_csv('jumlah_penduduk_sulawesi_barat.csv', index=False)
df_final.to_json('jumlah_penduduk_sulawesi_barat.json', orient='records')