In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv('Data Gorontalo Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,55.6,53.8,109.4
1,5/9/01,48.8,46.9,95.8
2,10/14/01,47.3,45.7,93.0
3,15-19,53.7,51.4,105.1
4,20-24,54.2,52.0,106.2
5,25-29,54.0,51.9,105.9
6,30-34,51.5,49.6,99.9
7,35-39,47.5,46.0,93.5
8,40-44,44.1,42.9,87.0
9,45-49,41.1,40.4,81.6
10,50-54,36.2,36.1,72.2
11,55-59,30.6,31.1,61.7
12,60-64,24.1,25.1,49.2
13,65-69,16.8,18.2,35.1
14,70-74,10.8,12.3,23.1
15,75+,9.8,12.7,22.5
16,Jumlah/Total,626.1,616.2,1242.2

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     626100     616200            1242300

In [4]:
df_final.to_csv('jumlah_penduduk_gorontalo.csv', index=False)
df_final.to_json('jumlah_penduduk_gorontalo.json', orient='records')