In [1]:
import pandas as pd
import json

In [5]:
data = pd.read_csv('Data Papua Selatan Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,0-4,28.14,27.08,55.22
1,5/9/26,47.03,45.16,92.19
2,10/14/26,33.27,33.12,66.39
3,15-19,23.87,21.57,45.44
4,20-24,19.37,16.50,35.87
5,25-29,19.98,17.83,37.81
6,30-34,19.07,17.99,37.06
7,35-39,19.95,18.52,38.47
8,40-44,18.52,16.17,34.69
9,45-49,14.88,13.23,28.11
10,50-54,12.77,10.82,23.59
11,55-59,8.97,8.55,17.52
12,60-64,7.92,6.90,14.82
13,65-69,4.62,4.91,9.53
14,70-74,3.48,3.19,6.67
15,75+,3.19,3.07,6.26
16,Jumlah/Total,285.03,264.61,549.64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [8]:
df = data.copy()

df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])

df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]

total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) * 1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]) * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk

}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     285030     264610             549640

In [9]:
df_final.to_csv('jumlah_penduduk_papua_selatan.csv', index=False)
df_final.to_json('jumlah_penduduk_papua_selatan.json', orient='records')