In [23]:
import pandas as pd

data = pd.read_csv(
    "Data_Lampung_Kotor.csv"
)

display(data.tail())


total_laki = 4857470
total_perempuan = 4665440


total_keseluruhan = (
    total_laki + total_perempuan
)

# dataframe final
df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv
df_final.to_csv(
    'jumlah_penduduk_lampung.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_lampung.json',
    orient='records',
    indent=4
)

,Kelompok Umur (75+),Jumlah Penduduk Menurut Kelompok Umur dan Jenis Kelamin (ribu jiwa),Unnamed: 2
14,60-64,200.07,193.47
15,65-69,149.24,142.73
16,70-74,101.32,98.25
17,75+,96.35,100.21
18,Jumlah,4857.47,4665.44

   laki_laki  perempuan  total_keseluruhan
0    4857470    4665440            9522910