In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("Data Banten Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,494.5,474.7,969.2
1,5/9/01,529.7,505.3,1035.1
2,10/14/01,531.3,507.4,1038.7
3,15-19,512.4,482.1,994.5
4,20-24,511.3,482.9,994.2
5,25-29,528.8,503.4,1032.3
6,30-34,524.1,503.5,1027.6
7,35-39,517.4,501.5,1019.0
8,40-44,485.0,473.8,958.7
9,45-49,445.5,440.0,885.6
10,50-54,386.1,382.1,768.2
11,55-59,315.3,310.7,626.0
12,60-64,244.5,241.8,486.3
13,65-69,169.5,166.7,336.2
14,70-74,106.7,107.7,214.4
15,75+,67.6,84.0,151.6
16,Jumlah/Total,6369.7,6167.7,12537.4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])

df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]

total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) *1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]) * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    6369700    6167700           12537400

In [4]:
df_final.to_csv('jumlah_penduduk_banten.csv', index=False)
df_final.to_json('jumlah_penduduk_banten.json', orient='records')