In [25]:
import pandas as pd
import json

In [26]:
data = pd.read_csv('Data Bali Kotor.csv', skiprows=2)
display(data)
display(data.info())

   Unnamed: 0  Laki-laki  Perempuan  Laki-Laki + Perempuan
0         NaN     2025.0     2025.0                 2025.0
1      4/1/00      165.6      159.0                  324.6
2      5/9/01      151.2      144.1                  295.3
3    10/14/01      153.2      146.0                  299.1
4       15-19      168.5      157.6                  326.1
5       20-24      170.4      161.4                  331.8
6       25-29      169.2      163.0                  332.1
7       30-34      167.1      163.0                  330.1
8       35-39      163.1      161.9                  325.0
9       40-44      160.4      160.8                  321.2
10      45-49      161.9      163.8                  325.8
11      50-54      150.7      153.6                  304.3
12      55-59      136.0      139.4                  275.4
13      60-64      113.0      117.8                  230.8
14      65-69       84.6       90.6                  175.2
15      70-74       59.1       66.0                  125.1
16        75+       60.4       78.9                  139.3
17     Jumlah     2234.6     2226.7                 4461.3

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             17 non-null     object
 1   Laki-laki              18 non-null     float64
 2   Perempuan              18 non-null     float64
 3   Laki-Laki + Perempuan  18 non-null     float64
dtypes: float64(3), object(1)
memory usage: 708.0+ bytes

None

In [37]:
df = data.copy()
df.drop(index=0, inplace=True)
df_clean = df[df['Unnamed: 0'].str.contains('Jumlah', na=False, case=False)]
display(df_clean)

   Unnamed: 0  Laki-laki  Perempuan  Laki-Laki + Perempuan
17     Jumlah     2234.6     2226.7                 4461.3

In [40]:
total_laki = int(pd.to_numeric(df_clean['Laki-laki'].iloc[0]) * 1000)
total_perempuan = int(pd.to_numeric(df_clean['Perempuan'].iloc[0]) * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

In [43]:
df_final.to_csv('jumlah_penduduk_bali.csv', index=False)
display(df_final)

df_final.to_json('jumlah_penduduk_bali.json', orient='records', indent=4, index=False)

   laki_laki  perempuan  total_keseluruhan
0    2234600    2226700            4461300