In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("Data Kep Riau Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,98.8,94.8,193.6
1,5/9/01,96.8,91.9,188.6
2,10/14/01,96.2,91.3,187.4
3,15-19,88.5,83.6,172.1
4,20-24,89.5,86.2,175.7
5,25-29,91.4,90.8,182.2
6,30-34,89.8,89.9,179.7
7,35-39,91.1,91.9,183.0
8,40-44,86.2,86.4,172.6
9,45-49,81.3,79.7,161.0
10,50-54,69.7,67.1,136.8
11,55-59,53.4,49.3,102.6
12,60-64,39.2,36.1,75.3
13,65-69,24.7,23.0,47.6
14,70-74,14.8,14.2,28.9
15,75+,12.6,13.6,26.2
16,Kepulauan Riau\n,1123.8,1089.7,2213.5

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [5]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Kepulauan Riau\n', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    1123800    1089700            2213500

In [6]:
df_final.to_csv('jumlah_penduduk_kep_riau.csv', index=False)
df_final.to_json('jumlah_penduduk_kep_riau.json', orient='records')