In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv('Data Sulawesi Utara Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,103.0,98.8,201.7
1,5/9/01,101.0,96.7,197.8
2,10/14/01,105.1,100.5,205.6
3,15-19,105.0,97.7,202.7
4,20-24,105.8,98.3,204.2
5,25-29,109.2,101.7,210.8
6,30-34,107.0,100.1,207.1
7,35-39,102.4,95.6,198.0
8,40-44,99.0,92.6,191.6
9,45-49,96.7,91.3,188.0
10,50-54,88.9,84.8,173.6
11,55-59,79.8,77.4,157.2
12,60-64,66.0,65.7,131.7
13,65-69,50.2,51.8,102.1
14,70-74,34.2,36.9,71.1
15,75+,35.0,43.3,78.3
16,Jumlah/Total,1388.2,1333.2,2721.4

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    1388200    1333200            2721400

In [4]:
df_final.to_csv('jumlah_penduduk_sulawesi_utara.csv', index=False)
df_final.to_json('jumlah_penduduk_sulawesi_utara.json', orient='records')