In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv("Data Jawa Barat Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,2032.4,1951.1,3983.5
1,5/9/01,1990.1,1899.3,3889.3
2,10/14/01,1962.2,1875.6,3837.8
3,15-19,2067.3,1943.9,4011.1
4,20-24,2067.7,1949.3,4017.0
5,25-29,2078.3,1974.8,4053.2
6,30-34,2044.9,1968.1,4013.0
7,35-39,1997.2,1945.8,3943.0
8,40-44,1889.1,1860.4,3749.5
9,45-49,1777.4,1776.8,3554.2
10,50-54,1581.0,1590.2,3171.3
11,55-59,1349.4,1359.1,2708.5
12,60-64,1084.9,1101.1,2186.0
13,65-69,797.2,810.4,1607.6
14,70-74,530.7,553.6,1084.3
15,75+,432.3,517.4,949.7
16,Jumlah/Total,25682.1,25076.9,50759.0
17,NaN,NaN,NaN,NaN
18,Catatan,NaN,NaN,NaN
19,Hasil Proyeksi Penduduk Jawa Barat 2020 -2035...,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            19 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 772.0+ bytes

None

In [4]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) *1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]) *1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0   25682100   25076900           50759000

In [5]:
df_final.to_csv('jumlah_penduduk_jawa_barat.csv', index=False)
df_final.to_json('jumlah_penduduk_jawa_barat.json', orient='records')