In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv('Data Papua Tengah Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,0-4,76.64,73.68,150.32
1,5/9/26,55.28,52.56,107.84
2,10/14/26,65.66,61.50,127.16
3,15-19,57.46,48.23,105.69
4,20-24,61.52,50.63,112.15
5,25-29,69.18,57.88,127.06
6,30-34,72.11,63.07,135.18
7,35-39,66.48,63.70,130.18
8,40-44,66.93,61.59,128.52
9,45-49,56.94,51.90,108.84
10,50-54,49.86,42.38,92.24
11,55-59,37.45,29.89,67.34
12,60-64,25.78,19.49,45.27
13,65-69,15.65,11.00,26.65
14,70-74,8.71,5.98,14.69
15,75+,7.84,5.37,13.21
16,Jumlah/Total,793.49,698.85,1492.34

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [6]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])

df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]) * 1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]) * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     793490     698850            1492340

In [7]:
df_final.to_csv('jumlah_penduduk_papua_tengah.csv', index=False)
df_final.to_json('jumlah_penduduk_papua_tengah.json', orient='records')