In [1]:
import pandas as pd
import json

In [4]:
data = pd.read_csv('Data DKI Jakarta Kotor.csv', skiprows=2)
display(data)
display(data.info())

   Unnamed: 0  Laki-laki  Perempuan    Jumlah
0         NaN       2025       2025      2025
1      4/1/00     369414     354957    724371
2      5/9/01     397165     378512    775677
3    10/14/01     404052     384816    788868
4       15-19     413092     392642    805734
5       20-24     413802     398186    811988
6       25-29     410712     400420    811132
7       30-34     409226     404359    813585
8       35-39     424269     422385    846654
9       40-44     418832     417145    835977
10      45-49     411427     409344    820771
11      50-54     369974     369731    739705
12      55-59     311385     313553    624938
13      60-64     245428     253633    499061
14        65+     362049     417465    779514
15     Jumlah    5360827    5317148  10677975

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  15 non-null     object
 1   Laki-laki   16 non-null     int64
 2   Perempuan   16 non-null     int64
 3   Jumlah      16 non-null     int64
dtypes: int64(3), object(1)
memory usage: 644.0+ bytes

None

In [8]:
df = data.copy()
df = df.drop(columns=['Jumlah'])

df_jumlah = df[df['Unnamed: 0'].str.contains('Jumlah', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Laki-laki'].iloc[0]))
total_perempuan = int(pd.to_numeric(df_jumlah['Perempuan'].iloc[0]))
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    5360827    5317148           10677975

In [9]:
df_final.to_csv('jumlah_penduduk_dki_jakarta.csv', index=False)
df_final.to_json('jumlah_penduduk_dki_jakarta.json', orient='records')