In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("Data Maluku Utara Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,63.5,60.9,124.4
1,5/9/01,60.4,60.0,120.4
2,10/14/01,57.2,60.2,117.3
3,15-19,60.3,62.0,122.3
4,20-24,59.6,58.1,117.7
5,25-29,56.8,50.4,107.2
6,30-34,59.1,51.0,110.1
7,35-39,60.0,55.5,115.5
8,40-44,53.2,48.5,101.7
9,45-49,47.3,41.2,88.5
10,50-54,38.4,34.8,73.3
11,55-59,29.4,28.6,58.0
12,60-64,22.7,22.8,45.5
13,65-69,16.4,16.2,32.6
14,70-74,11.2,10.8,22.0
15,75+,8.4,8.9,17.3
16,Jumlah/Total,704.0,669.8,1373.8

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     704000     669800            1373800

In [4]:
df_final.to_csv('jumlah_penduduk_maluku_utara.csv', index=False)
df_final.to_json('jumlah_penduduk_maluku_utara.json', orient='records')