In [1]:
import pandas as pd
import json

In [4]:
data = pd.read_csv('Data Papua Pegunungan Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,0-4,75.51,72.62,148.13
1,5/9/26,38.50,35.92,74.42
2,10/14/26,50.86,47.40,98.26
3,15-19,53.09,43.77,96.86
4,20-24,67.38,56.86,124.24
5,25-29,78.73,65.60,144.33
6,30-34,74.83,62.85,137.68
7,35-39,68.38,58.19,126.57
8,40-44,58.81,55.38,114.19
9,45-49,59.78,55.91,115.69
10,50-54,47.77,47.13,94.90
11,55-59,44.00,37.50,81.50
12,60-64,30.52,26.66,57.18
13,65-69,23.23,15.85,39.08
14,70-74,11.66,7.83,19.49
15,75+,8.03,4.31,12.34
16,Jumlah/Total,791.08,693.78,1073.60

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [6]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
display(df)

df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]

total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)']).iloc[0] * 1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)']).iloc[0] * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk

}])
display(df_final)

   Kelompok Umur  Penduduk (Laki-Laki) (Ribu)  Penduduk (Perempuan) (Ribu)
0            0-4                        75.51                        72.62
1         5/9/26                        38.50                        35.92
2       10/14/26                        50.86                        47.40
3          15-19                        53.09                        43.77
4          20-24                        67.38                        56.86
5          25-29                        78.73                        65.60
6          30-34                        74.83                        62.85
7          35-39                        68.38                        58.19
8          40-44                        58.81                        55.38
9          45-49                        59.78                        55.91
10         50-54                        47.77                        47.13
11         55-59                        44.00                        37.50
12         60-64                        30.52                        26.66
13         65-69                        23.23                        15.85
14         70-74                        11.66                         7.83
15           75+                         8.03                         4.31
16  Jumlah/Total                       791.08                       693.78

   laki_laki  perempuan  total_keseluruhan
0     791080     693780            1484860

In [7]:
df_final.to_csv('jumlah_penduduk_papua_pegunungan.csv', index=False)
df_final.to_json('jumlah_penduduk_papua_pegunungan.json', orient='records')