In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv('Data Sulawesi Tengah Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,136.6,130.9,267.6
1,5/9/01,139.8,134.1,273.9
2,10/14/01,136.8,131.5,268.3
3,15-19,135.3,126.3,261.6
4,20-24,133.8,124.4,258.2
5,25-29,136.0,126.5,262.5
6,30-34,131.0,122.5,253.5
7,35-39,122.5,116.0,238.4
8,40-44,113.6,108.1,221.8
9,45-49,105.5,100.8,206.3
10,50-54,92.4,88.4,180.9
11,55-59,76.9,73.7,150.6
12,60-64,60.7,58.6,119.3
13,65-69,43.3,42.3,85.6
14,70-74,28.5,28.5,57.0
15,75+,24.5,26.2,50.7
16,Jumlah/Total,1617.2,1538.9,3156.1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    1617200    1538900            3156100

In [4]:
df_final.to_csv('jumlah_penduduk_sulawesi_tengah.csv', index=False)
df_final.to_json('jumlah_penduduk_sulawesi_tengah.json', orient='records')