In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv('Data Sulawesi Tenggara Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,137.5,134.3,271.8
1,5/9/01,128.3,125.0,253.3
2,10/14/01,125.8,122.6,248.5
3,15-19,128.1,120.6,248.7
4,20-24,125.5,118.4,243.9
5,25-29,123.6,118.3,241.9
6,30-34,116.9,112.7,229.6
7,35-39,107.5,104.6,212.1
8,40-44,97.6,95.4,192.9
9,45-49,87.8,86.1,173.9
10,50-54,75.0,74.1,149.1
11,55-59,60.6,60.1,120.7
12,60-64,47.1,47.3,94.4
13,65-69,33.2,34.1,67.3
14,70-74,21.9,23.3,45.1
15,75+,19.8,23.8,43.6
16,Jumlah/Total,1436.3,1400.5,2836.7
17,NaN,NaN,NaN,NaN
18,Catatan,NaN,NaN,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            18 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 740.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0    1436300    1400500            2836800

In [4]:
df_final.to_csv('jumlah_penduduk_sulawesi_tenggara.csv', index=False)
df_final.to_json('jumlah_penduduk_sulawesi_tenggara.json', orient='records')