In [16]:
import pandas as pd

data = pd.read_csv(
    "Data_Bengkulu_Kotor.csv",
    sep=';'
)

display(data.tail())

   Jumlah penduduk menurut jenis kelamin Unnamed: 1  Unnamed: 2  Unnamed: 3
12                                53.846     51.504         NaN         NaN
13                                42.636     40.994         NaN         NaN
14                                30.901     29.712         NaN         NaN
15                                20.108      19.99         NaN         NaN
16                                15.491     18.656         NaN         NaN

In [18]:
import pandas as pd

# total penduduk Bengkulu 2025
total_laki = 1091256
total_perempuan = 1046788

total_keseluruhan = (
    total_laki + total_perempuan
)

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv
df_final.to_csv(
    'jumlah_penduduk_bengkulu.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_bengkulu.json',
    orient='records',
    indent=4
)

   laki_laki  perempuan  total_keseluruhan
0    1091256    1046788            2138044