In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv('Data Papua Barat Daya Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,0-4,33.55,32.22,65.77
1,5/9/26,25.15,23.98,49.13
2,10/14/26,23.90,23.09,46.99
3,15-19,27.78,25.70,53.48
4,20-24,28.96,26.27,55.23
5,25-29,29.76,27.44,57.20
6,30-34,29.82,27.10,56.92
7,35-39,28.08,25.23,53.31
8,40-44,25.24,22.74,47.98
9,45-49,21.50,19.47,40.97
10,50-54,17.75,16.00,33.75
11,55-59,13.76,12.18,25.94
12,60-64,10.35,9.46,19.81
13,65-69,7.36,6.63,13.99
14,70-74,4.80,4.34,9.14
15,75+,3.45,3.38,6.83
16,Jumlah/Total,331.21,305.23,636.44

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [6]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)']).iloc[0] * 1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)']).iloc[0] * 1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk

}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     331210     305230             636440

In [7]:
df_final.to_csv('jumlah_penduduk_papua_barat_daya.csv', index=False)
df_final.to_json('jumlah_penduduk_papua_barat_daya.json', orient='records')