In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("Data Maluku Kotor.csv", skiprows=2)
display(data)
display(data.info())

   Unnamed: 0  Laki-laki  Perempuan  Laki-laki+Perempuan
0         NaN       2025       2025                 2025
1      4/1/00      96198      92248               188446
2      5/9/01      80426      77107               157533
3    10/14/01      77477      74423               151900
4       15-19      92181      85520               177701
5       20-24      92336      86093               178429
6       25-29      90384      85655               176039
7       30-34      84474      81180               165654
8       35-39      75215      73907               149122
9       40-44      66894      66677               133571
10      45-49      58682      59549               118231
11      50-54      50211      51553               101764
12      55-59      41349      42871                84220
13      60-64      32838      34511                67349
14      65-69      24462      26045                50507
15      70-74      16566      17942                34508
16        75+      16474      19115                35589
17     Jumlah     996167     974396              1970563

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           17 non-null     object
 1   Laki-laki            18 non-null     int64
 2   Perempuan            18 non-null     int64
 3   Laki-laki+Perempuan  18 non-null     int64
dtypes: int64(3), object(1)
memory usage: 708.0+ bytes

None

In [3]:
df = data.copy()
df.drop(index=0, inplace=True)
df_clean = df[df['Unnamed: 0'].str.contains('Jumlah', na=False, case=False)]
display(df_clean)

   Unnamed: 0  Laki-laki  Perempuan  Laki-laki+Perempuan
17     Jumlah     996167     974396              1970563

In [4]:
total_laki = int(pd.to_numeric(df_clean['Laki-laki'].iloc[0]) )
total_perempuan = int(pd.to_numeric(df_clean['Perempuan'].iloc[0]))
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])
display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     996167     974396            1970563

In [5]:
df_final.to_csv('jumlah_penduduk_maluku.csv', index=False)
df_final.to_json('jumlah_penduduk_maluku.json', orient='records')