In [29]:
import pandas as pd

data = pd.read_csv(
    "Data_Kalimantan_Tengah_Kotor.csv",
    sep=';'
)

display(data.tail())


total_laki = 1450000
total_perempuan = 1370000


total_keseluruhan = (
    total_laki + total_perempuan
)


df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_keseluruhan
}])

display(df_final)

# simpan csv
df_final.to_csv(
    'jumlah_penduduk_kalimantan_tengah.csv',
    index=False
)

# simpan json
df_final.to_json(
    'jumlah_penduduk_kalimantan_tengah.json',
    orient='records',
    indent=4
)

   Kabupaten/Kota/Provinsi,[Proyeksi Penduduk SP2020] Penduduk Menurut Kabupaten/Kota dan Jenis Kelamin di Provinsi Kalimantan Tengah (ribu orang),
12                             Gunung Mas,77.73,70.51
13                           Barito Timur,61.39,58.82
14                            Murung Raya,62.17,58.06
15                         Palangka Raya,157.56,156.8
16                  Kalimantan Tengah,1467.14,1377.85

   laki_laki  perempuan  total_keseluruhan
0    1450000    1370000            2820000