In [1]:
import pandas as pd
import json

In [2]:
data = pd.read_csv("Data Babel Kotor.csv")
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,67.3,64.5,131.8
1,5/9/01,61.3,58.3,119.5
2,10/14/01,60.1,57.2,117.3
3,15-19,64.7,60.9,125.6
4,20-24,65.0,61.4,126.5
5,25-29,64.3,61.5,125.7
6,30-34,63.7,60.6,124.3
7,35-39,64.3,60.3,124.6
8,40-44,60.9,56.7,117.6
9,45-49,56.7,52.1,108.8
10,50-54,49.2,45.2,94.4
11,55-59,39.3,36.7,76.0
12,60-64,30.7,29.3,60.0
13,65-69,22.2,22.0,44.3
14,70-74,14.5,15.0,29.5
15,75+,11.2,13.8,24.9
16,Jumlah/Total,795.2,755.6,1550.8

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     float64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     float64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     float64
dtypes: float64(3), object(1)
memory usage: 676.0+ bytes

None

In [3]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0])*1000)
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0])*1000)
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0     795200     755600            1550800

In [4]:
df_final.to_csv('jumlah_penduduk_babel.csv', index=False)
df_final.to_json('jumlah_penduduk_babel.json', orient='records')