In [1]:
import pandas as pd
import json

In [3]:
data = pd.read_csv('Data Jawa Tengah Kotor.csv')
display(data)
display(data.info())

,Kelompok Umur,Penduduk (Laki-Laki) (Ribu),Penduduk (Perempuan) (Ribu),Penduduk (Laki-Laki + Perempuan) (Ribu)
0,4/1/00,1453486,1395492,2848978
1,5/9/01,1378005,1314670,2692675
2,10/14/01,1388617,1324616,2713233
3,15-19,1434037,1349663,2783700
4,20-24,1453872,1371580,2825452
5,25-29,1488450,1405197,2893647
6,30-34,1478667,1407466,2886133
7,35-39,1457127,1406076,2863203
8,40-44,1404285,1376799,2781084
9,45-49,1344073,1352647,2696720
10,50-54,1229032,1260829,2489861
11,55-59,1100859,1156162,2257021
12,60-64,920100,984473,1904573
13,65-69,721747,779311,1501058
14,70-74,500418,558377,1058795
15,75+,450659,587141,1037800
16,Jumlah/Total,19203434,19030499,38233933

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 4 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Kelompok Umur                            17 non-null     object
 1   Penduduk (Laki-Laki) (Ribu)              17 non-null     int64
 2   Penduduk (Perempuan) (Ribu)              17 non-null     int64
 3   Penduduk (Laki-Laki + Perempuan) (Ribu)  17 non-null     int64
dtypes: int64(3), object(1)
memory usage: 676.0+ bytes

None

In [5]:
df = data.copy()
df = df.drop(columns=['Penduduk (Laki-Laki + Perempuan) (Ribu)'])
df_jumlah = df[df['Kelompok Umur'].str.contains('Jumlah/Total', na=False, case=False)]
total_laki = int(pd.to_numeric(df_jumlah['Penduduk (Laki-Laki) (Ribu)'].iloc[0]))
total_perempuan = int(pd.to_numeric(df_jumlah['Penduduk (Perempuan) (Ribu)'].iloc[0]))
total_penduduk = total_laki + total_perempuan

df_final = pd.DataFrame([{
    'laki_laki': total_laki,
    'perempuan': total_perempuan,
    'total_keseluruhan': total_penduduk
}])

display(df_final)

   laki_laki  perempuan  total_keseluruhan
0   19203434   19030499           38233933

In [6]:
df_final.to_csv('jumlah_penduduk_jawa_tengah.csv', index=False)
df_final.to_json('jumlah_penduduk_jawa_tengah.json', orient='records')